name: oh-docker-tags-action-test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: get commit message
        run: |
          echo ::set-env name=COMMIT_MESSAGE::$(git log --format=%B -n 1 ${{ github.event.after }})
          echo $COMMIT_MESSAGE
      - name: Docker Build And Push Image
        uses: scheduleonce/oh-docker-tag-action@1.0.4
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        id: test
        with:
          branchName: $ {{GITHUB_REF}}
          dockerServer: dockerServer
          username: username
          password: password
          pullId: 123
          ImageTag: test
          commitMessagePattern: TEST-[0-9]+
          tagMap: |
            test~>dev
            live~>master
            special/~>
