name: oh-docker-tags-action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build And Push Image
        uses: scheduleonce/oh-docker-tag-action@1.0.3
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        if: github.event.pull_request.merged == true
        id: test
        with:
          branchName: $ {{GITHUB_REF}}
          dockerServer: dockerServer
          username: username
          password: password
          tagMap: |
            test~>dev
            live~>master
            special/~>
      - name: get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run: echo $commitmsg
      - name: test
        if: "!contains(github.event.head_commit.message, 'test')"
        run: echo "Found Test"
      - name: Test pattern
        if: startsWith(github.event.head_commit.message, 'test-[0-9]*')
        run: echo "Found Test ID"
